controller_list:
  - name: fake_kuka_1_controller
    type: $(arg execution_type)
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
initial:  # Define initial robot poses.
  - group: kuka_1
    pose: home